module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Jangli',
];

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Smart',
    'Group Gym',
    'Horse Gym',
    'Ghost Town',
    'Gym',
    'Dispersed Gym',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Gym',
    'Hunting Gym',
    'Cliffs',
    'Hollow',
];
